# Site settings
title: "Nulad Wisnu Pambudi"
description: "Nulad Wisnu Pambudi resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Nulad W. Pambudi"
resume_title:                   "Senior Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "nuladwisnupambudi@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+62 852 1138 5794"
resume_contact_address:         "Jalan Margonda Raya Gg Ciliwung Rt 05/01, Depok"

resume_header_contact_info:     "Jalan Margonda Raya Gg Ciliwung Rt 05/01, Depok • +62 852 1138 5794 • nuladwisnupambudi@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>I’m a problem-solving oriented software engineer; dividing problems to bite-sized chunk, applying logic and sprinkle some code to solve it really gets me going. Fortunate enough to experience solving problems in several knowledge domains, such as internal enterprise application, Australia's regional government regulatory in the fields of property & housing, B2B marketplace system, loyalty & reward program and cloud telephony services. Have a dream to design and implement robust and effective solutions as an architect. In the middle of becoming polyglot in multiple systems, with experience in .NET, Node.JS, PHP and Golang.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/nulad"
  resume_twitter_url:           "http://twitter.com/nuladwpambudi"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/nulad-pambudi"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://nulad.github.io/resume"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
